import AVFoundation

/// Speech engine for the agents. Prefers a REAL neural voice generated by the
/// Mac relay (free local Piper TTS) and plays it back; falls back to the
/// on-device Apple voice if the relay or its TTS is unavailable. Each agent
/// passes its own `voice` model so they sound like different people.
final class AgentVoice: NSObject, AVSpeechSynthesizerDelegate, AVAudioPlayerDelegate, @unchecked Sendable {
    private let synthesizer = AVSpeechSynthesizer()
    private var player: AVAudioPlayer?
    private let lock = NSLock()
    private var playbackContinuation: CheckedContinuation<Void, Never>?
    private let appleQueue = SpeechQueueBox()

    override init() {
        super.init()
        synthesizer.delegate = self
    }

    var isSpeaking: Bool { synthesizer.isSpeaking || (player?.isPlaying ?? false) }

    /// The engine that produced the LAST playback ("elevenlabs", "piper",
    /// or "apple") — callers badge "Paid voice" off this.
    private(set) var lastEngine = "apple"

    /// Speak `text`. Uses the relay's neural voice when available, else Apple.
    /// Suspends until playback finishes (or `stop()` is called).
    ///
    /// VOICE-COST POLICY: `premium` may be requested ONLY by external,
    /// revenue-facing flows (sales/customer calls, demos, marketing). It is
    /// double-gated: the owner's settings toggle here, and the relay's
    /// character budget on the Mac. Everything internal stays on this
    /// default (free voice) — do NOT pass premium for in-app conversation.
    func speak(_ text: String, seedFrom id: String,
               voice model: String? = nil, relay: HermesRelayConfiguration? = nil,
               premium: Bool = false) async {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        // Claim the audio session for playback (otherwise the silent switch
        // mutes everything). Not deactivated afterwards — see VoiceNoteRecorder.
        let session = AVAudioSession.sharedInstance()
        try? session.setCategory(.playback, mode: .spokenAudio, options: [.duckOthers])
        try? session.setActive(true)

        let tier = (premium && VoicePolicy.premiumEnabled) ? "premium" : "internal"
        if let relay, relay.isConfigured, let model,
           let result = await Self.fetchNeural(trimmed, voice: model, relay: relay, tier: tier) {
            lastEngine = result.engine
            await play(result.data)
        } else {
            lastEngine = "apple"
            await speakApple(trimmed, seedFrom: id)
        }
    }

    func stop() {
        synthesizer.stopSpeaking(at: .immediate)
        appleQueue.drain()
        player?.stop()
        player = nil
        resumePlayback()
    }

    // MARK: Neural playback

    private func play(_ data: Data) async {
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            lock.lock()
            playbackContinuation?.resume()       // displace any prior waiter
            playbackContinuation = continuation
            lock.unlock()
            do {
                let newPlayer = try AVAudioPlayer(data: data)
                newPlayer.delegate = self
                player = newPlayer
                if !newPlayer.play() { resumePlayback() }
            } catch {
                resumePlayback()                 // bad audio → don't hang
            }
        }
    }

    private func resumePlayback() {
        lock.lock()
        let waiter = playbackContinuation
        playbackContinuation = nil
        lock.unlock()
        waiter?.resume()
    }

    nonisolated func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
        resumePlayback()
    }

    nonisolated func audioPlayerDecodeErrorDidOccur(_ player: AVAudioPlayer, error: Error?) {
        resumePlayback()
    }

    private static func fetchNeural(_ text: String, voice: String,
                                    relay: HermesRelayConfiguration,
                                    tier: String = "internal") async -> (data: Data, engine: String)? {
        guard let baseURL = relay.baseURL else { return nil }
        var request = URLRequest(url: baseURL.appending(path: "tts"))
        request.httpMethod = "POST"
        request.timeoutInterval = 30
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("Bearer \(relay.token)", forHTTPHeaderField: "Authorization")
        request.httpBody = try? JSONSerialization.data(
            withJSONObject: ["text": text, "voice": voice, "tier": tier])
        guard let (data, response) = try? await URLSession.shared.data(for: request),
              let http = response as? HTTPURLResponse, http.statusCode == 200,
              !data.isEmpty else { return nil }
        let engine = (http.value(forHTTPHeaderField: "X-Voice-Engine") ?? "piper").lowercased()
        return (data, engine)
    }

    // MARK: Apple fallback

    private func speakApple(_ text: String, seedFrom id: String) async {
        appleQueue.increment()
        synthesizer.speak(Self.utterance(for: text, seedFrom: id))
        await appleQueue.waitUntilIdle()
    }

    private static func utterance(for text: String, seedFrom id: String) -> AVSpeechUtterance {
        let seed = id.unicodeScalars.reduce(0) { $0 + Int($1.value) }
        let utterance = AVSpeechUtterance(string: text)
        if let voice = bestVoice(seed: seed) {
            utterance.voice = voice
        }
        utterance.pitchMultiplier = 0.97 + Float(seed % 4) / 50.0
        utterance.rate = AVSpeechUtteranceDefaultSpeechRate * (0.97 + Float(seed % 3) / 50.0)
        return utterance
    }

    /// Best intelligible Apple voice, excluding the robotic legacy synths.
    private static func bestVoice(seed: Int) -> AVSpeechSynthesisVoice? {
        let mainstream: Set<String> = ["en-US", "en-GB", "en-AU", "en-IE"]
        let usable = AVSpeechSynthesisVoice.speechVoices().filter { voice in
            let id = voice.identifier.lowercased()
            return mainstream.contains(voice.language)
                && !id.contains("eloquence") && !id.contains("novelty")
        }
        guard !usable.isEmpty else { return AVSpeechSynthesisVoice(language: "en-US") }
        func rank(_ v: AVSpeechSynthesisVoice) -> Int {
            var score = v.quality == .premium ? 300 : (v.quality == .enhanced ? 200 : 100)
            if v.identifier.lowercased().contains("siri") { score += 50 }
            return score
        }
        let top = usable.map(rank).max() ?? 0
        let pool = usable.filter { rank($0) == top }.sorted { $0.identifier < $1.identifier }
        return pool.isEmpty ? usable.first : pool[seed % pool.count]
    }

    nonisolated func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didFinish utterance: AVSpeechUtterance) {
        appleQueue.decrement()
    }

    nonisolated func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didCancel utterance: AVSpeechUtterance) {
        appleQueue.decrement()
    }
}

/// Thread-safe pending-utterance counter with a single idle-waiter.
final class SpeechQueueBox: @unchecked Sendable {
    private let lock = NSLock()
    private var pending = 0
    private var continuation: CheckedContinuation<Void, Never>?

    func increment() {
        lock.lock(); pending += 1; lock.unlock()
    }

    func decrement() {
        lock.lock()
        pending = max(0, pending - 1)
        let waiter = pending == 0 ? continuation : nil
        if pending == 0 { continuation = nil }
        lock.unlock()
        waiter?.resume()
    }

    func waitUntilIdle() async {
        await withCheckedContinuation { (new: CheckedContinuation<Void, Never>) in
            lock.lock()
            if pending == 0 {
                lock.unlock()
                new.resume()
                return
            }
            let old = continuation
            continuation = new
            lock.unlock()
            old?.resume()
        }
    }

    func drain() {
        lock.lock()
        pending = 0
        let waiter = continuation
        continuation = nil
        lock.unlock()
        waiter?.resume()
    }
}
