import SwiftUI

/// The Morning Briefing screen — generated by the Executive Secretary from
/// real data (today's meetings, overnight memo replies), readable or spoken.
struct BriefingView: View {
    @EnvironmentObject private var org: OrgStore
    @EnvironmentObject private var hub: MeetingHub
    @EnvironmentObject private var runtime: HermesRuntimeController
    @EnvironmentObject private var briefings: BriefingCenter
    @Environment(\.dismiss) private var dismiss

    private var secretaryID: String {
        (org.agent(id: "executive_assistant") ?? org.ceo)?.id ?? "executive_assistant"
    }

    var body: some View {
        NavigationStack {
            ZStack {
                HermesTheme.background.ignoresSafeArea()
                ScrollView {
                    VStack(alignment: .leading, spacing: 16) {
                        header

                        if briefings.isGenerating {
                            HStack(spacing: 10) {
                                ProgressView().controlSize(.small)
                                Text("Your secretary is preparing the briefing…")
                                    .font(.subheadline)
                                    .foregroundStyle(HermesTheme.textSecondary)
                            }
                            .hermesCard()
                        } else if !briefings.briefing.isEmpty {
                            Text(briefings.briefing)
                                .font(.body)
                                .foregroundStyle(HermesTheme.textPrimary)
                                .fixedSize(horizontal: false, vertical: true)
                                .hermesCard(padding: 16)

                            HStack(spacing: 12) {
                                Button {
                                    briefings.toggleSpeech(secretaryID: secretaryID)
                                } label: {
                                    Label(briefings.isSpeaking ? "Stop" : "Read it to me",
                                          systemImage: briefings.isSpeaking ? "stop.fill" : "speaker.wave.2.fill")
                                }
                                .buttonStyle(.borderedProminent)
                                .tint(HermesTheme.emerald)

                                Button {
                                    Task { await briefings.generate(org: org, hub: hub, relay: runtime.relayConfiguration) }
                                } label: {
                                    Label("Refresh", systemImage: "arrow.clockwise")
                                }
                                .buttonStyle(.bordered)
                            }
                        } else {
                            Button {
                                Task { await briefings.generate(org: org, hub: hub, relay: runtime.relayConfiguration) }
                            } label: {
                                Label("Prepare my briefing", systemImage: "sunrise.fill")
                                    .frame(maxWidth: .infinity)
                                    .font(.headline)
                                    .padding(.vertical, 6)
                            }
                            .buttonStyle(.borderedProminent)
                            .tint(HermesTheme.emerald)
                        }

                        if let error = briefings.lastError {
                            Text(error).font(.caption).foregroundStyle(.orange)
                        }

                        settings
                    }
                    .padding(16)
                }
            }
            .navigationTitle("Morning Briefing")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) { Button("Done") { dismiss() } }
            }
        }
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(greeting)
                .font(.title2.weight(.bold))
                .foregroundStyle(HermesTheme.textPrimary)
            if let at = briefings.generatedAt {
                Text("Prepared \(at.formatted(date: .abbreviated, time: .shortened)) by your Executive Secretary")
                    .font(.caption)
                    .foregroundStyle(HermesTheme.textSecondary)
            }
        }
    }

    private var greeting: String {
        switch Calendar.current.component(.hour, from: Date()) {
        case 5..<12: "Good morning ☀️"
        case 12..<18: "Good afternoon"
        default: "Good evening"
        }
    }

    private var settings: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("DAILY BRIEFING")
                .font(.system(size: 11, weight: .bold))
                .tracking(2)
                .foregroundStyle(HermesTheme.textSecondary)

            Toggle(isOn: $briefings.notifyDaily) {
                Label("Notify me every morning", systemImage: "bell.badge.fill")
                    .font(.subheadline)
            }
            .tint(HermesTheme.emerald)

            if briefings.notifyDaily {
                Picker("At", selection: $briefings.notifyHour) {
                    ForEach(5..<12, id: \.self) { hour in
                        Text("\(hour):00").tag(hour)
                    }
                }
                .pickerStyle(.segmented)
            }
        }
        .hermesCard()
    }
}
